### ISSUE TITLE
No Copyright notice

### ISSUE THREAD

**Issue by mans0954** [fdurand/Net-Cisco-MSE-REST#1]
As far as I can see, Net-Cisco-MSE-REST is missing a copyright notice. A copyright notice is necessary in order to place code under the GPL[1]. Please could you add a copyright notice? Thanks.

[1] https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by fdurand** [comment]
Thanks, done in 39ef3df6bb343ccd6c82ee17e5e48ad4ff9ffd86

**Comment by mans0954** [comment]
@fdurand  thanks for the quick response - however, I'm afraid that's still not a copyright notice. You need a line which says:

Copyright 2016 Fabrice Durand <fdurand@inverse.ca>

Or possibly:

Copyright 2016 Inverse inc.

Depending on whether you or Inverse Inc. are the copyright holder.

**Comment by mans0954** [comment]
Also, you've now introduced an ambiguity in that README says Perl licence (Artistic or GPL-1+) whereas  Net-Cisco-MSE-REST/lib/Net/Cisco/MSE/REST.pm says GPL-3+.
